spring.application.name=gestion_compras

spring.datasource.url=jdbc:postgresql://localhost:5432/Palmera_Junior
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Schema por defecto

spring.jpa.properties.hibernate.default_schema=dep_compras


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect