spring.application.name=gestion_compras

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/Palmera_Junior
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=dep_compras
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Config para login con Outlook
# spring.security.oauth2.client.registration.microsoft.client-id=XXXXX
# spring.security.oauth2.client.registration.microsoft.client-secret=XXXXX
# spring.security.oauth2.client.registration.microsoft.scope=profile,email